version: '3.8'

services:
  # Local PostgreSQL for testing
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: carfinder_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d carfinder_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend for local testing
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: "postgresql://test_user:test_pass@postgres-test:5432/carfinder_test"
    depends_on:
      postgres-test:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend for local testing
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:8001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "start"]

volumes:
  postgres_test_data: