apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: test-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Car Finder - DEV Environment</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
            .container { max-width: 600px; margin: 0 auto; }
            .status { color: green; font-size: 24px; }
            .info { background: #f0f0f0; padding: 20px; border-radius: 5px; margin: 20px 0; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚗 Car Finder Platform</h1>
            <div class="status">✅ DEV Environment is Running!</div>
            <div class="info">
                <h3>Infrastructure Status</h3>
                <p>✅ GKE Cluster: dev-gke-cluster</p>
                <p>✅ Database: PostgreSQL (dev-postgres-bbf5771d)</p>
                <p>✅ Storage: Cloud Storage buckets</p>
                <p>✅ Monitoring: Configured</p>
            </div>
            <p>Your car finder platform infrastructure is ready for application deployment!</p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
  - port: 80
    targetPort: 80