apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-finder-frontend
  namespace: default
  labels:
    app: car-finder-frontend
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-finder-frontend
  template:
    metadata:
      labels:
        app: car-finder-frontend
        environment: dev
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: frontend-build
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: frontend-build
        configMap:
          name: frontend-build-files
      - name: nginx-config
        configMap:
          name: frontend-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: car-finder-frontend-service
  namespace: default
  labels:
    app: car-finder-frontend
spec:
  type: LoadBalancer
  selector:
    app: car-finder-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None