name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run frontend tests
      run: |
        cd frontend
        npm test -- --watchAll=false --coverage=false
      env:
        CI: true
    
    - name: Run backend tests
      run: |
        cd backend
        pytest test_main.py -v
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Validate Kubernetes manifests
      run: |
        echo "✅ Validating K8s manifests..."
        find k8s -name "*.yaml" -exec echo "Found: {}" \;
        echo "✅ Manifest validation completed"